### PR TITLE
Sourisseau2019 dms

### PR DESCRIPTION
**Pull request by skhilton**
Zika Virus DMS data from Sourisseau _et al._, 2019. 

Here is a view of the data on this branch: https://dms-view.github.io/?markdown-url=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-view%2Fzika%2FSourisseau2019-DMS%2Fdata%2FEnvelope%2FSourisseau2019%2FSourisseau2019_DMS.md&data-url=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-view%2Fzika%2FSourisseau2019-DMS%2Fdata%2FEnvelope%2FSourisseau2019%2FSourisseau2019_DMS.csv&condition=raw+preferences&site_metric=site_entropy&mutation_metric=mut_pref&selected_sites=T+335&pdb-url=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-view%2Fzika%2FSourisseau2019-DMS%2Fdata%2FEnvelope%2FSourisseau2019%2F5ire.pdb

I would like some feedback on whether or not this is the correct data to display and if there is a better way to organize it. For instance, is RSA useful? Should I exclude the mutational effects data? Should I include the natural frequencies data? 

After we merge this PR, I will update the link in the top-level readme.

### CODE REVIEW

**Comment by skhilton** [comment]
Closes issue #1

**Review by jbloom — CHANGES_REQUESTED** [review]
@skhilton: Looks pretty good. I had the following suggestions:

1. I think including RSA could be helpful, but make the manifest explain RSA is relative solvent accessibility, not sure if everyone would know this.

2. I think it would be nice if the default highlight was something more interesting. For instance, I think the paper highlights (FIG 3C) both the conserved fusion loop and glycan loop. Maybe having it show one of these (maybe fusion loop?) in default link that the view goes to might be nice?

3. I think showing natural frequencies could be nice, just explicitly say these are as calculated in 2019 in the paper---as we won't be updating them.

**Comment by skhilton** [comment]
@jbloom: Okay, that all sounds good! Are you okay with the "unscaled" mutational effects being shown for both the raw and unscaled preferences? Do you know of a link to mutational effects with the rescaled preferences?

**Comment by skhilton** [comment]
@jbloom: I forgot to add to my list of questions: Is it okay to only select one protein chain?

**Comment by jbloom** [comment]
For Zika, I feel like it might be best to color both monomers in the dimer because I think at least one of the antibody epitopes spans a monomer interface.

Similarly, for HIV, have you asked Adam his opinion on whether data should be shown on monomer or trimer?

**Comment by skhilton** [comment]
@jbloom: Okay, sounds good, I will look into that. I've asked him to review one of the HIV datasets so I will follow up with him about that.  

Do you have thought on the whether the mutational effects should be calculated separately for the raw vs scaled prefs?

**Comment by jbloom** [comment]
I suppose if it says scaled and unscaled then they should so the numerical values of mutational effects stay aligned with preferences? But it doesn't really matter if someone isn't paying attention to y-axis values, since re-scaling preferences is just a linear transformation on mutational effects.

**Comment by skhilton** [comment]
@jbloom: update on this PR

- I added a definition for RSA
- I rescaled the mutational effects for the rescaled preferences by multiplying them by 1.65 
- I added the natural frequencies 

I do need some help on the protein structure. I saw on the pdb database that the E protein is chains A, C, and E in 5ire.pdb. But E is a dimer? I am having trouble squaring that without a site->chain/site map. Do you have insight into this?

**Comment by jbloom** [comment]
@skhilton: Looks like in paper we just showed chains C and E as the dimer (https://github.com/jbloomlab/ZIKV_DMS_with_EvansLab/blob/master/pymol_scripts/5ire_postamble.txt#L1).

So I'd suggest you do that. If you can't easily select, you can just make a modified PDB (e.g., `5ire_C_and_E.pdb`) and use that.

**Comment by skhilton** [comment]
@jbloom: okay,  think this is now ready to merge but if you want to take a quick look that would be appreciated! 

https://dms-view.github.io/?markdown-url=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-view%2Fzika%2FSourisseau2019-DMS%2Fdata%2FEnvelope%2FSourisseau2019%2FSourisseau2019_DMS.md&pdb-url=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-view%2Fzika%2FSourisseau2019-DMS%2Fdata%2FEnvelope%2FSourisseau2019%2F5ire_C_E.pdb&data-url=https%3A%2F%2Fraw.githubusercontent.com%2Fdms-view%2Fzika%2FSourisseau2019-DMS%2Fdata%2FEnvelope%2FSourisseau2019%2FSourisseau2019_DMS.csv&condition=raw+preferences&site_metric=site_entropy&mutation_metric=mut_pref&selected_sites=

**Comment by jbloom** [comment]
I think it looks good, but could you make it highlight sites in some region of interest (such as conserved fusion loop as described in paper?) by default?

**Comment by skhilton** [comment]
@jbloom: Great! And yes I will follow your advice for something interesting for the link in the top-level README.

**Pull request merged**
